// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoService.DB.Migrations.Contexts;

namespace VideoService.Data.Migrations
{
    [DbContext(typeof(VideoServiceDbContext))]
    [Migration("20210703113550_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoService.Data.Entities.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Flows");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        },
                        new
                        {
                            Id = 11
                        },
                        new
                        {
                            Id = 12
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.FlowsToVideos", b =>
                {
                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("FlowId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("FlowsToVideos");

                    b.HasData(
                        new
                        {
                            FlowId = 1,
                            VideoId = 3
                        },
                        new
                        {
                            FlowId = 3,
                            VideoId = 4
                        },
                        new
                        {
                            FlowId = 4,
                            VideoId = 5
                        },
                        new
                        {
                            FlowId = 4,
                            VideoId = 7
                        },
                        new
                        {
                            FlowId = 5,
                            VideoId = 9
                        },
                        new
                        {
                            FlowId = 5,
                            VideoId = 10
                        },
                        new
                        {
                            FlowId = 5,
                            VideoId = 11
                        },
                        new
                        {
                            FlowId = 6,
                            VideoId = 12
                        },
                        new
                        {
                            FlowId = 6,
                            VideoId = 13
                        },
                        new
                        {
                            FlowId = 6,
                            VideoId = 14
                        },
                        new
                        {
                            FlowId = 7,
                            VideoId = 18
                        },
                        new
                        {
                            FlowId = 7,
                            VideoId = 19
                        },
                        new
                        {
                            FlowId = 7,
                            VideoId = 20
                        },
                        new
                        {
                            FlowId = 8,
                            VideoId = 21
                        },
                        new
                        {
                            FlowId = 8,
                            VideoId = 22
                        },
                        new
                        {
                            FlowId = 8,
                            VideoId = 23
                        },
                        new
                        {
                            FlowId = 9,
                            VideoId = 23
                        },
                        new
                        {
                            FlowId = 9,
                            VideoId = 24
                        },
                        new
                        {
                            FlowId = 9,
                            VideoId = 25
                        },
                        new
                        {
                            FlowId = 10,
                            VideoId = 26
                        },
                        new
                        {
                            FlowId = 10,
                            VideoId = 27
                        },
                        new
                        {
                            FlowId = 10,
                            VideoId = 28
                        },
                        new
                        {
                            FlowId = 11,
                            VideoId = 15
                        },
                        new
                        {
                            FlowId = 11,
                            VideoId = 16
                        },
                        new
                        {
                            FlowId = 11,
                            VideoId = 17
                        },
                        new
                        {
                            FlowId = 12,
                            VideoId = 29
                        },
                        new
                        {
                            FlowId = 12,
                            VideoId = 30
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.GroupsToFlows", b =>
                {
                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("FlowId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupsToFlows");

                    b.HasData(
                        new
                        {
                            FlowId = 3,
                            GroupId = 4,
                            Priority = 1
                        },
                        new
                        {
                            FlowId = 4,
                            GroupId = 5,
                            Priority = 2
                        },
                        new
                        {
                            FlowId = 10,
                            GroupId = 7,
                            Priority = 2
                        },
                        new
                        {
                            FlowId = 11,
                            GroupId = 8,
                            Priority = 1
                        },
                        new
                        {
                            FlowId = 12,
                            GroupId = 8,
                            Priority = 2
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.GroupsToVideos", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("VideoId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupsToVideos");

                    b.HasData(
                        new
                        {
                            VideoId = 2,
                            GroupId = 1,
                            Priority = 2
                        },
                        new
                        {
                            VideoId = 3,
                            GroupId = 2,
                            Priority = 2
                        },
                        new
                        {
                            VideoId = 4,
                            GroupId = 3,
                            Priority = 2
                        },
                        new
                        {
                            VideoId = 8,
                            GroupId = 5,
                            Priority = 1
                        },
                        new
                        {
                            VideoId = 9,
                            GroupId = 6,
                            Priority = 2
                        },
                        new
                        {
                            VideoId = 12,
                            GroupId = 6,
                            Priority = 0
                        },
                        new
                        {
                            VideoId = 22,
                            GroupId = 7,
                            Priority = 1
                        },
                        new
                        {
                            VideoId = 24,
                            GroupId = 7,
                            Priority = 2
                        },
                        new
                        {
                            VideoId = 15,
                            GroupId = 9,
                            Priority = 3
                        },
                        new
                        {
                            VideoId = 16,
                            GroupId = 9,
                            Priority = 3
                        },
                        new
                        {
                            VideoId = 17,
                            GroupId = 9,
                            Priority = 3
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToFlows", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FlowId");

                    b.HasIndex("FlowId");

                    b.ToTable("UsersToFlows");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            FlowId = 1,
                            Priority = 3
                        },
                        new
                        {
                            UserId = 4,
                            FlowId = 2,
                            Priority = 3
                        },
                        new
                        {
                            UserId = 5,
                            FlowId = 4,
                            Priority = 1
                        },
                        new
                        {
                            UserId = 6,
                            FlowId = 5,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 6,
                            FlowId = 6,
                            Priority = 2
                        },
                        new
                        {
                            UserId = 7,
                            FlowId = 7,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 7,
                            FlowId = 8,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 7,
                            FlowId = 9,
                            Priority = 1
                        },
                        new
                        {
                            UserId = 9,
                            FlowId = 12,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 10,
                            FlowId = 11,
                            Priority = 2
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToGroups", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UsersToGroups");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            GroupId = 1
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 4,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 4,
                            GroupId = 4
                        },
                        new
                        {
                            UserId = 5,
                            GroupId = 5
                        },
                        new
                        {
                            UserId = 6,
                            GroupId = 6
                        },
                        new
                        {
                            UserId = 7,
                            GroupId = 7
                        },
                        new
                        {
                            UserId = 7,
                            GroupId = 8
                        },
                        new
                        {
                            UserId = 8,
                            GroupId = 7
                        },
                        new
                        {
                            UserId = 8,
                            GroupId = 9
                        },
                        new
                        {
                            UserId = 9,
                            GroupId = 7
                        },
                        new
                        {
                            UserId = 9,
                            GroupId = 8
                        },
                        new
                        {
                            UserId = 10,
                            GroupId = 7
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToVideos", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("UsersToVideos");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            VideoId = 1,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 2,
                            VideoId = 2,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 3,
                            VideoId = 3,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 4,
                            VideoId = 4,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 5,
                            VideoId = 5,
                            Priority = 1
                        },
                        new
                        {
                            UserId = 5,
                            VideoId = 6,
                            Priority = 2
                        },
                        new
                        {
                            UserId = 5,
                            VideoId = 7,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 7,
                            VideoId = 15,
                            Priority = 1
                        },
                        new
                        {
                            UserId = 7,
                            VideoId = 16,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 7,
                            VideoId = 17,
                            Priority = 2
                        },
                        new
                        {
                            UserId = 8,
                            VideoId = 16,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 8,
                            VideoId = 21,
                            Priority = 1
                        },
                        new
                        {
                            UserId = 8,
                            VideoId = 22,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 8,
                            VideoId = 23,
                            Priority = 0
                        },
                        new
                        {
                            UserId = 10,
                            VideoId = 30,
                            Priority = 3
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Video 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Video 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Video 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Video 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Video 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Video 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Video 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Video 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Video 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Video 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Video 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Video 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Video 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Video 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Video 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Video 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Video 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Video 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Video 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Video 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Video 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Video 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Video 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Video 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Video 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Video 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Video 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Video 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Video 30"
                        });
                });

            modelBuilder.Entity("VideoService.Data.Entities.FlowsToVideos", b =>
                {
                    b.HasOne("VideoService.Data.Entities.Flow", "Flow")
                        .WithMany("FlowsToVideos")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.Video", "Video")
                        .WithMany("FlowsToVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoService.Data.Entities.GroupsToFlows", b =>
                {
                    b.HasOne("VideoService.Data.Entities.Flow", "Flow")
                        .WithMany("GroupsToFlows")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.Group", "Group")
                        .WithMany("GroupsToFlows")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoService.Data.Entities.GroupsToVideos", b =>
                {
                    b.HasOne("VideoService.Data.Entities.Group", "Group")
                        .WithMany("GroupsToVideos")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.Video", "Video")
                        .WithMany("GroupsToVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToFlows", b =>
                {
                    b.HasOne("VideoService.Data.Entities.Flow", "Flow")
                        .WithMany("UsersToFlows")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.User", "User")
                        .WithMany("UsersToFlows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToGroups", b =>
                {
                    b.HasOne("VideoService.Data.Entities.Group", "Group")
                        .WithMany("UsersToGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.User", "User")
                        .WithMany("UsersToGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoService.Data.Entities.UsersToVideos", b =>
                {
                    b.HasOne("VideoService.Data.Entities.User", "User")
                        .WithMany("UsersToVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoService.Data.Entities.Video", "Video")
                        .WithMany("UsersToVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
